 import React from 'react';
 import './Privacy.css';

 const PrivacyPolicy = () => {
  return (

    <div className=' privacy-container '>
    <h5 className='privacyHeading'> Privacy & Cookies</h5>
    <div className='privacy-box '>
    <p className='privacyParagraph'>
    <b>Privacy Policy</b> <br /> Last updated: March 15, 2021 <br /> This Privacy
    Policy delineates Our policies and procedures on the collection, use and
    disclosure of Your information when You use the Service and tells You
    about Your privacy rights and how the law protects You. <br />
    We use Your Personal data to provide and improve the Service. By using
    the Service, you agree to the collection and use of information in
    accordance with this Privacy Policy.

    <br /> <b>Interpretation and Definitions</b>

    <br />
    <b>Interpretation</b>
    <br />

    The words of which the initial letter is capitalized have meanings
    defined under the following conditions. The following definitions shall
    have the same meaning regardless of whether they appear in singular or
    in plural.
    <br />
    <br />
    <b>Definitions</b>
    <br />

    For the purposes of this Privacy Policy:
    </p>
    <ul>
    <li> <b>Account </b> means a unique account created for You to access our Service or parts of our Service.</li>
    <li> <b>Business,</b> for the purpose of the business, we primarily operate in Pakistan and UK. Our company is registered in UK under the online company registration laws 2020.</li>
    <li> <b>Company</b> (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to UXT CLAN (along with Address).</li>

    </ul> 
    <p>For the purpose of the GDPR, the Company is the Data Controller.</p>
    <ul>
    <li><b>Consumer,</b> for the purpose The Data Protection Act 2018, means a natural person who is a UK resident. A resident, as defined in the law, includes (1) every individual who is in the UK for other than a temporary or transitory purpose, and (2) every individual who is domiciled in the UK who is outside the UK for a temporary or transitory purpose.</li>
    <li><b>Cookies </b>are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
    <li><b>Country </b>refers to: London, United Kingdom</li>
    <li><b>Data Controller,</b> for the purposes of the GDPR (General Data Protection Regulation), refers to the Company as the legal person which alone or jointly with others determines the purposes and means of the processing of Personal Data.</li>
    <li><b>Device </b>means any device that can access the Service such as a computer, a cellphone or a digital tablet</li>
    <li><b>Personal</b> Data is any information that relates to an identified or identifiable individual.</li>
    </ul> 
    <p className='privacyParagraph'>For the purposes for GDPR, Personal Data means any information relating to You such as a name, an identification number, location data, online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity.</p>
    <p>For the purposes of the GDPR, Personal Data means any information that identifies, relates to, describes or is capable of being associated with, or could reasonably be linked, directly or indirectly, with You.</p>
    <ul>
     <li> <b> Sale, </b> for the purpose of The Data Protection Act 2018, means selling, renting, releasing, disclosing, disseminating, making available, transferring, or otherwise communicating orally, in writing, or by electronic or other means, a Consumer’s personal information to another business or a third party for monetary or other valuable consideration.</li>
    <li> <b> Service </b>refers to the Website.</li>
    <li> <b> Service Provider</b> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. For the purpose of the GDPR, Service Providers are considered Data Processors.</li>
    <li> <b>Third-party Social Media </b>Service refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
    <li> <b>Usage Data </b> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
    <li> <b>Website</b> refers to UXT CLAN Limited, accessible from <a href="#">https://uxtclan.com</a></li>
    <li> <b> You </b> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
    </ul>
    <p>Under GDPR (General Data Protection Regulation), You can be referred to as the Data Subject or as the User as you are the individual using the Service.</p>
    <p> <b>Collecting and Using Your Personal Data</b> </p>
    <p> <b>Types of Data Collected</b> </p>
    <p> <b>Personal Data</b> </p>
    <p>While using Our Service, we may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
    <ul>
   
    <li>Email address</li>
    <li>First name and last name</li>
    <li>Phone number</li>
    <li>Address, State, Province, ZIP/Postal code, City</li>
    <li> Usage Data</li>
    </ul>
     <p><b> Usage Data</b> </p>
<p>
Usage Data is collected automatically when using the Service
<br/>

Usage Data may include information such as Your Device’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
<br/>
When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
<br/>
We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
</p>
 <p><b>Information from Third-Party Social Media Services</b> </p>
 <p>The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:</p>
 <ul>
    <li>Google</li>
    <li>Facebook</li>
    <li>Twitter</li>
    </ul>
    <p>If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, we may collect Personal data that is already associated with Your Third-Party Social Media Service’s account, such as Your name, Your email address, Your activities or Your contact list associated with that account.
    <br/>
    You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service’s account. If You choose to provide such information and Personal Data, during registration or otherwise, you are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.</p>
<p><b>Tracking Technologies and Cookies</b> </p>
<p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
<ul>
   
    <li><b>Cookies or Browser Cookies.</b> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, you may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
    <li><b>Flash Cookies.</b> Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies. For more information on how You can delete Flash Cookies, please read “Where can I change the settings for disabling, or deleting local shared objects?” available at <a href="#"> https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_</a></li>
    <li><b>Web Beacons. </b>Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
    </ul>
    <p>Cookies can be “Persistent” or “Session” Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies:<a href="#">What Are Cookies?</a></p>
    <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
    <ul><li><b>Necessary / Essential Cookies</b></li></ul>
    <p>Type: Session Cookies</p> 
     <p>Administered by: Us</p>
     <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p> 
 <ul><li><b>Cookies Policy / Notice Acceptance Cookies</b></li></ul>
    <p>Type: Persistent Cookies</p> 
     <p>Administered by: Us</p>
     <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
      <ul><li><b>Functionality Cookies</b></li></ul>
    <p>Type: Persistent Cookies</p> 
     <p>Administered by: Us</p>
     <p>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
     <ul><li><b>Tracking and Performance Cookies</b></li></ul>
    <p>Type: Persistent Cookies</p> 
     <p>Administered by: Third-Parties</p>
     <p>Purpose: These Cookies are used to track information about traffic to the Website and how users use the Website. The information gathered via these Cookies may directly or indirectly identify you as an individual visitor. This is because the information collected is typically linked to a pseudonymous identifier associated with the device you use to access the Website. We may also use these Cookies to test new pages, features or new functionality of the Website to see how our users react to them.</p>
    <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
    <p><b>Use of Your Personal Data</b></p>
    <p>The Company may use Personal Data for the following purposes:</p>

<ul>
   
    <li> <b> To provide and maintain our Service,</b> including to monitor the usage of our Service.</li>
    <li> <b> To manage Your Account:</b> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
    <li> <b> For the performance of a contract:</b> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
    <li> <b> To contact You: </b>To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application’s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
    <li> <b> To provide You </b>with news special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
    <li> <b> To manage Your requests: </b> To attend and manage Your requests to Us.</li>
    <li> <b> To deliver targeted advertising to You:</b> We may use Your information to develop and display content and advertising (and work with third-party vendors who do so) tailored to Your interests and/or location and to measure its effectiveness.</li>
    <li> <b> For business transfers:</b> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
    <li> <b> For other purposes: </b>We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>

    </ul>
    <p>We may share Your personal information in the following situations:</p>
    <ul>
   
    <li><b>With Service Providers:</b> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to advertise on third party websites to You after You visited our Service, to contact You.</li>
    <li><b>For business transfers: </b>We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
    <li><b>With Affiliates:</b> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
    <li><b>With business partners:</b> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
    <li> <b>With other users: </b>when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.</li>
    <li><b>With Your consent:</b> We may disclose Your personal information for any other purpose with Your consent.</li>
    </ul>
    <p><b>Retention of Your Personal Data</b></p>
    <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
    <br/>
    The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
    <p><b>Transfer of Your Personal Data</b></p>
    <p>Your information, including Personal Data, is processed at the Company’s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
    <br/>
    Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
    <br/>
    The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
    </p>
    <p><b>Disclosure of Your Personal Data</b></p>
    <small><b>Business Transactions</b></small>
    <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
     
     <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
    
      <small><b> Other legal requirements</b></small>
      <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
    <ul>
    <li>Comply with a legal obligation</li>
    <li>Protect and defend the rights or property of the Company</li>
    <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
    <li>Protect the personal safety of Users of the Service or the public</li>
    <li>Protect against legal liability</li>
    </ul>
    <small><b>Security of Your Personal Data</b></small>
    <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
    <small><b>Detailed Information on the Processing of Your Personal Data</b></small>
    <p>Service Providers have access to Your Personal Data only to perform their tasks on Our behalf and are obligated not to disclose or use it for any other purpose.</p>
     <small><b>Analytics</b></small>
     <p>We may use third-party Service providers to monitor and analyze the use of our Service.</p>
<ul>
    <li><b>Google Analytics</b></li>
    </ul>
    <p>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</p>
    
    <p>You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js and dc.js) from sharing information with Google Analytics about visits activity.</p>
<p>For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="#">https://policies.google.com/privacy</a></p>

<small><b>Email Marketing</b></small>
<p>We may use Your Personal Data to contact You with newsletters, marketing or promotional materials and other information that may be of interest to You. You may opt-out of receiving any, or all, of these communications from Us by following the unsubscribe link or instructions provided in any email We send or by contacting Us.
<br/>We may use Email Marketing Service Providers to manage and send emails to You.</p>
<ul>
    <li><b> Mailchimp</b></li>
    </ul>
    <p>Mailchimp is an email marketing sending service provided by The Rocket Science Group LLC.
    <br/>
    For more information on the privacy practices of MailChimp, please visit their Privacy policy:
    <a href="#"> https://mailchimp.com/legal/privacy/2</a>
    <br/>
    Google Ads (AdWords) remarketing service is provided by Google Inc.
    <br/>
    You can opt-out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the Google Ads Settings page: 
    <a href="http://www.google.com/settings/ads">http://www.google.com/settings/ads</a>
    <br/>
    Google also recommends installing the Google Analytics Opt-out Browser Add-on – 
    <br/>
    <a href="https://tools.google.com/dlpage/gaoptout ">http:https://tools.google.com/dlpage/gaoptout </a>
    – for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics.
    <br/>
    For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: 
    <a href="https://policies.google.com/privacy" >https://policies.google.com/privacy</a>
    </p>
    <ul>
    <li><b>Twitter</b></li>
    </ul>
    <p>Twitter remarketing service is provided by Twitter Inc.
    <br/>
    You can opt-out from Twitter’s interest-based ads by following their instructions: 
    <a href="https://support.twitter.com/articles/20170405" >https://support.twitter.com/articles/20170405</a>
    </p>
<p>Twitter remarketing service is provided by Twitter Inc.
    <br/>
    You can learn more about the privacy practices and policies of Twitter by visiting their Privacy Policy page:  
    <a href="https://twitter.com/privacy" >https://twitter.com/privacy</a>
    </p>
    <ul>
    <li><b>Facebook</b></li>
    </ul>
    <p>Facebook remarketing service is provided by Facebook Inc
    <br/>
    You can learn more about interest-based advertising from Facebook by visiting this page: 
    <a href="https://www.facebook.com/help/164968693837950" >https://www.facebook.com/help/164968693837950</a>
    </p>
<p>
    To opt-out from Facebook’s interest-based ads, follow these instructions from Facebook: 
    <a href="https://www.facebook.com/help/164968693837950" >https://www.facebook.com/help/164968693837950</a>
    </p>
    <p>
    Facebook adheres to the Self-Regulatory Principles for Online Behavioral Advertising established by the Digital
     Advertising Alliance. You can also opt-out from Facebook and other participating companies through the
      Digital Advertising Alliance in the USA<a href="http://www.aboutads.info/choices/" >http://www.aboutads.info/choices/</a>
        , the Digital Advertising Alliance
       of Canada in Canada <a href="http://youradchoices.ca/" >http://youradchoices.ca/ </a> or the European Interactive Digital Advertising
     Alliance in Europe http://www.youronlinechoices.eu/, or opt-out using your mobile device settings.</p>
<p>For more information on the privacy practices of Facebook, please visit Facebook’s Data Policy: <a href="https://www.facebook.com/privacy/explanation">https://www.facebook.com/privacy/explanation</a></p>
<p><b>GDPR Privacy</b></p>
<p><b>Legal Basis for Processing Personal Data under GDPR</b></p>
<p>We may process Personal Data under the following conditions:</p>

<ul>
   
    <li> <b> Consent:</b> You have given Your consent for processing Personal Data for one or more specific purposes.</li>
    <li> <b> Performance of a contract:</b> Provision of Personal Data is necessary for the performance of an agreement with You and/or for any pre-contractual obligations thereof.</li>
    <li> <b> Legal obligations: </b>Processing Personal Data is necessary for compliance with a legal obligation to which the Company is subject.</li>
    <li> <b> Vital interests: </b>Processing Personal Data is necessary in order to protect Your vital interests or of another natural person.</li>
    <li> <b> Public interests:</b> Processing Personal Data is related to a task that is carried out in the public interest or in the exercise of official authority vested in the Company.</li>
    <li> <b> Legitimate interests:</b> Processing Personal Data is necessary for the purposes of the legitimate interests pursued by the Company.</li>
    </ul>
    <p>In any case, the Company will gladly help to clarify the specific legal basis that applies to the processing, and in particular whether the provision of Personal Data is a statutory or contractual requirement, or a requirement necessary to enter into a contract.</p>
    <p><b>Your Rights under the GDPR</b></p>
    <p>The Company undertakes to respect the confidentiality of Your Personal Data and to guarantee You can exercise Your rights.
    <br/>
    You have the right under this Privacy Policy, and by law if You are within the EU, to:
    </p>

<ul>
   
    <li> <b> Request access to Your Personal Data. </b> The right to access, update or delete the information We have on You. Whenever made possible, you can access, update or request deletion of Your Personal Data directly within Your account settings section. If you are unable to perform these actions yourself, please contact Us to assist You. 
    This also enables You to receive a copy of the Personal Data We hold about You.</li>
    <li> <b> Request correction of the Personal Data that We hold about You. </b> You have the right to to have any incomplete or inaccurate information We hold about You corrected.</li>
    <li> <b> Object to processing of Your Personal Data. </b>  This right exists where We are relying on a legitimate interest as the legal basis for Our processing and there is something about Your particular situation, which makes You want to object to our processing of Your Personal Data on this ground. You also have the right to object where We are processing Your Personal Data for direct marketing purposes.</li>
    <li> <b> Request erasure of Your Personal Data. </b>  You have the right to ask Us to delete or remove Personal Data when there is no good reason for Us to continue processing it.</li>
    <li> <b> Request the transfer of Your Personal Data.</b>  We will provide to You, or to a third-party You have chosen, Your Personal Data in a structured, commonly used, machine-readable format. Please note that this right only applies to automated information which You initially provided consent for Us to use or where We used the information to perform a contract with You.</li>
    <li> <b> Withdraw Your consent.</b>  You have the right to withdraw Your consent on using your Personal Data. If You withdraw Your consent, We may not be able to provide You with access to certain specific functionalities of the Service.</li>
    </ul>
<p><b>Exercising of Your GDPR Data Protection Rights</b></p>
<p>You may exercise Your rights of access, rectification, cancellation and opposition by contacting Us. Please note that we may ask You to verify Your identity before responding to such requests. If You make a request, We will try our best to respond to You as soon as possible.
<br/>
You have the right to complain to a Data Protection Authority about Our collection and use of Your Personal Data. For more information, if You are in the European Economic Area (EEA), please contact Your local data protection authority in the EEA.
</p>
<p>This privacy notice section for California residents supplements the information contained in Our Privacy Policy and it applies solely to all visitors, users, and others who reside in the State of California.</p>
<p><b>Categories of Personal Information Collected</b></p>
<p>We collect information that identifies, relates to, describes, references, is capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular Consumer or Device. The following is a list of categories of personal information which we may collect or may have been collected from California residents within the last twelve (12) months.
<br/>
Please note that the categories and examples provided in the list below are those defined in the CCPA. This does not mean that all examples of that category of personal information were in fact collected by Us, but reflects our good faith belief to the best of our knowledge that some of that information from the applicable category may be and may have been collected. For example, certain categories of personal information would only be collected if You provided such personal information directly to Us.
</p>
<ul> <li><b>Category A: Identifiers.</b></li></ul>
<p>Examples: A real name, alias, postal address, unique personal identifier, online identifier, Internet Protocol address, email address, account name, driver’s license number, passport number, or other similar identifiers.
<br/>Collected: Yes.</p>
<ul> <li><b>Category B: Commercial information.</b></li></ul>
<p>Examples: Records and history of products or services purchased or considered.<br/>Collected: Yes.</p>

<ul> <li><b>Category C: Biometric information.</b></li></ul>
<p>Examples: Genetic, physiological, behavioral, and biological characteristics, or activity patterns used to extract a template or other identifier or identifying information, such as, fingerprints, faceprints, and voiceprints, iris or retina scans, keystroke, gait, or other physical patterns, and sleep, health, or exercise data. <br/>Collected: Yes.</p>
<ul> <li><b>Category D: Internet or other similar network activity.</b></li></ul>
<p>Examples: Interaction with our Service or advertisement. <br/>Collected: Yes.</p>


<ul> <li><b>• Category E: Geolocation data.</b></li></ul>
<p>Examples: Approximate physical location. <br/>Collected: No.</p>

<ul> <li><b>Category F: Sensory data.</b></li></ul>
<p>Examples: Audio, electronic, visual, thermal, olfactory, or similar information. <br/>Collected: No.</p>

<ul> <li><b>Category G: Professional or employment-related information.</b></li></ul>
<p>Examples: <br/>Collected: Yes.</p>


<ul> <li><b>Category A: Identifiers.</b></li></ul>
<p>Examples: Current or past job history or performance evaluations. <br/>Collected: No.</p>


<p><b>Sale of Personal Information</b></p>
<p>As defined in the Data Protection Act 2018, “sell” and “sale” mean selling, renting, releasing, disclosing, disseminating, making available, transferring, or otherwise communicating orally, in writing, or by electronic or other means, a consumer’s personal information by the business to a third party for valuable consideration. This means that We may have received some kind of benefit in return for sharing personal Information, but not necessarily a monetary benefit.
<br/>Please note that the categories listed below are those defined in the CCPA. This does not mean that all examples of that category of personal information were in fact sold, but reflects our good faith belief to the best of our knowledge that some of that information from the applicable category may be and may have been shared for value in return.
<br/>We may sell and may have sold in the last twelve (12) months the following categories of personal information:
</p>
<ul>    <li> Category A: Identifiers</li>
    <li>Category D: Internet or other similar network activity</li>
    </ul>
<p><b>Share of Personal Information</b></p>
<p>We may share Your personal information identified in the above categories with the following categories of third parties:</p>
<ul>
    <li> Service Providers</li>
    <li>Our affiliates</li>
    <li> Our business partners</li>
    <li>Third party vendors to whom You or Your agents authorize Us to disclose Your personal information in connection with products or services We provide to You</li>
    </ul>
    <smal><b>Sale of Personal Information of Minors Under 16 Years of Age</b></smal>
<p>We do not sell the personal information of Consumers We actually know are less than 16 years of age, unless We receive affirmative authorization (the “right to opt-in”) from either the Consumer who is between 13 and 16 years of age, or the parent or guardian of a Consumer less than 13 years of age. Consumers who opt-in to the sale of personal information may opt-out of future sales at any time. To exercise the right to opt-out, You (or Your authorized representative) may submit a request to Us by contacting Us.
<br/>If You have reason to believe that a child under the age of 13 (or 16) has provided Us with personal information, please contact Us with sufficient detail to enable Us to delete that information.
</p>
<smal><b>Do Not Sell My Personal Information</b></smal>
<p>You have the right to opt-out of the sale of Your personal information. Once We receive and confirm a verifiable consumer request from You, we will stop selling Your personal information. To exercise Your right to opt-out, please contact Us.
<br/>The Service Providers we partner with (for example, our analytics or advertising partners) may use technology on the Service that sells personal information as defined by the CCPA law. If you wish to opt out of the use of Your personal information for interest-based advertising purposes and these potential sales as defined under the Data protection Act 2018, you may do so by following the instructions below.
<br/>
Please note that any opt out is specific to the browser You use. You may need to opt out on every browser that You use.
</p>
 <smal><b>Website</b></smal>
 <p>You can opt out of receiving ads that are personalized as served by our Service Providers by following our instructions presented on the Service:
 <br/>
 The opt out will place a cookie on Your computer that is unique to the browser You use to opt out. If you change browsers or delete the cookies saved by your browser, You will need to opt out again.</p>
 <smal><b>Mobile Devices</b></smal>
 <p>Your mobile device may give You the ability to opt out of the use of information about the apps You use in order to serve You ads that are targeted to Your interests:</p>
    <ul>
   
    <li>“Opt out of Interest-Based Ads” or “Opt out of Ads Personalization” on Android devices</li>
    <li>“Limit Ad Tracking” on iOS devices</li>
    </ul>
    <p>You can also stop the collection of location information from Your mobile device by changing the preferences on Your mobile device.</p>
 <smal><b>Changes to this Privacy Policy</b></smal>

<p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. </p>
<p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the “Last updated” date at the top of this Privacy Policy.</p>
<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page</p>

<smal><b>Contact Us</b></smal>
<p>If you have any questions about this Privacy Policy, You can contact us:</p>
<ul>
    <li>By visiting this page on our website:   <a href="https://uxtclan.com">https://uxtclan.com</a> </li>
</ul>



    </div>
    </div>
    );
};

export default PrivacyPolicy;





<ul>
   
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    </ul>